=== dn0912/web_trends_xml/xml/europe_countries/dtd_task/europecountries.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT europe_countries (country*)>
<!ELEMENT country (name, population, capital)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT population (#PCDATA)>
<!ELEMENT capital (#PCDATA)>

=== dn0912/web_trends_xml/xml/europe_countries/dtd_task/europecountries_css.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="europecountries.css" title="list" alternate="yes"?>
<?xml-stylesheet type="text/css" href="europecountries2.css" title="table" alternate="no"?>
<!-- created with XMLSpear -->
<!DOCTYPE europe_countries SYSTEM "europecountries.dtd">
<europe_countries>
   <country>
      <name>Germany</name>
      <population>82670000</population>
      <capital>Berlin</capital>
   </country>
   <country>
      <name>France</name>
      <population>66900000</population>
      <capital>Paris</capital>
   </country>
</europe_countries>
